-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 00:26:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soundgood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soundgood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soundgood` DEFAULT CHARACTER SET utf8 ;
USE `soundgood` ;

-- -----------------------------------------------------
-- Table `soundgood`.`Instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Instrument` (
  `instrumentID` INT NOT NULL,
  `type` VARCHAR(500) NOT NULL,
  `brand` VARCHAR(500) NOT NULL,
  `price` INT NOT NULL,
  `monthRented` INT NULL,
  `yearRented` INT NULL,
  PRIMARY KEY (`instrumentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Student` (
  `studentID` INT NOT NULL,
  `personID` INT NOT NULL,
  `admitted` TINYINT NOT NULL,
  PRIMARY KEY (`studentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Siblings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Siblings` (
  `studentID` INT NOT NULL,
  `siblingID` INT NOT NULL,
  PRIMARY KEY (`studentID`, `siblingID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Address` (
  `addressID` INT NOT NULL,
  `street` VARCHAR(500) NOT NULL,
  `zipCode` VARCHAR(500) NOT NULL,
  `city` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`addressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`StudentLesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`StudentLesson` (
  `studentID` INT NOT NULL,
  `lessonID` INT NOT NULL,
  PRIMARY KEY (`studentID`, `lessonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`TimeSlot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`TimeSlot` (
  `timeSlotID` INT NOT NULL,
  `teacherID` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  PRIMARY KEY (`timeSlotID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Lesson` (
  `lessonID` INT NOT NULL,
  `skill` INT NOT NULL,
  `teacherID` INT NOT NULL,
  `lessonType` INT NOT NULL,
  PRIMARY KEY (`lessonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`GroupLesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`GroupLesson` (
  `lessonID` INT NOT NULL,
  `maxStudents` INT NOT NULL,
  `minStudents` INT NOT NULL,
  `instrument` VARCHAR(500) NULL,
  PRIMARY KEY (`lessonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`IndividualLesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`IndividualLesson` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Ensamble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Ensamble` (
  `lessonID` INT NOT NULL,
  `maxStudents` INT NOT NULL,
  `minStudents` INT NOT NULL,
  `genre` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`lessonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Contact` (
  `contactID` INT NOT NULL,
  `contactTitle` VARCHAR(500) NOT NULL,
  `phoneNumber` VARCHAR(12) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`contactID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`KnownInstruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`KnownInstruments` (
  `personID` INT NOT NULL,
  `instrument` VARCHAR(500) NULL,
  PRIMARY KEY (`personID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Person` (
  `personID` INT NOT NULL,
  `teacherID` INT NULL,
  `studentID` INT NULL,
  `addressID` INT NOT NULL,
  `fullName` VARCHAR(500) NOT NULL,
  `personNumber` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`personID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Teacher` (
  `teacherID` INT NOT NULL,
  `personID` INT NOT NULL,
  `teachesEnsambles` TINYINT NOT NULL,
  PRIMARY KEY (`teacherID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`Price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`Price` (
  `lessonType` INT NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`lessonType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`PersonContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`PersonContact` (
  `personID` INT NOT NULL,
  `contactID` INT NOT NULL,
  PRIMARY KEY (`personID`, `contactID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`StudentInstrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`StudentInstrument` (
  `studentID` INT NOT NULL,
  `instrumentID` INT NOT NULL,
  PRIMARY KEY (`studentID`, `instrumentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundgood`.`LessonTimeSlot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundgood`.`LessonTimeSlot` (
  `lessonID` INT NOT NULL,
  `timeSlotID` INT NOT NULL,
  PRIMARY KEY (`timeSlotID`, `lessonID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
