-- MySQL Script generated by MySQL Workbench
-- Minor modifications made by hand by Viggo Hermansson
-- Mon Dec  5 00:26:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema soundgood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soundgood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS soundgood ;

-- -----------------------------------------------------
-- Table Instrument
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Instrument (
  instrumentID INT NOT NULL,
  type VARCHAR(500) NOT NULL,
  brand VARCHAR(500) NOT NULL,
  price INT NOT NULL,
  monthRented INT NULL,
  yearRented INT NULL,
  PRIMARY KEY (instrumentID)
);


-- -----------------------------------------------------
-- Table Student
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Student (
  studentID INT NOT NULL,
  personID INT NOT NULL,
  admitted INT NOT NULL,
  PRIMARY KEY (studentID)
);


-- -----------------------------------------------------
-- Table Siblings
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Siblings (
  studentID INT NOT NULL,
  siblingID INT NOT NULL,
  PRIMARY KEY (studentID, siblingID)
);


-- -----------------------------------------------------
-- Table Address
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Address (
  addressID INT NOT NULL,
  street VARCHAR(500) NOT NULL,
  zipCode VARCHAR(500) NOT NULL,
  city VARCHAR(500) NOT NULL,
  PRIMARY KEY (addressID)
);


-- -----------------------------------------------------
-- Table StudentLesson
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS StudentLesson (
  studentID INT NOT NULL,
  lessonID INT NOT NULL,
  PRIMARY KEY (studentID, lessonID)
);


-- -----------------------------------------------------
-- Table TimeSlot
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TimeSlot (
  timeSlotID INT NOT NULL,
  teacherID INT NOT NULL,
  time TIME NOT NULL,
  day INT NOT NULL,
  month INT NOT NULL,
  year INT NOT NULL,
  PRIMARY KEY (timeSlotID)
);


-- -----------------------------------------------------
-- Table Lesson
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Lesson (
  lessonID INT NOT NULL,
  skill INT NOT NULL,
  lessonType INT NOT NULL,
  PRIMARY KEY (lessonID)
);


-- -----------------------------------------------------
-- Table GroupLesson
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS GroupLesson (
  lessonID INT NOT NULL,
  maxStudents INT NOT NULL,
  minStudents INT NOT NULL,
  instrument VARCHAR(500) NULL,
  PRIMARY KEY (lessonID)
);


-- -----------------------------------------------------
-- Table IndividualLesson
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS IndividualLesson (
  lessonID INT NOT NULL,
  instrument VARCHAR(500) NULL,
  PRIMARY KEY (lessonID)
);


-- -----------------------------------------------------
-- Table Ensamble
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ensamble (
  lessonID INT NOT NULL,
  maxStudents INT NOT NULL,
  minStudents INT NOT NULL,
  genre VARCHAR(500) NOT NULL,
  PRIMARY KEY (lessonID)
);


-- -----------------------------------------------------
-- Table Contact
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Contact (
  contactID INT NOT NULL,
  contactTitle VARCHAR(500) NOT NULL,
  phoneNumber VARCHAR(12) NOT NULL,
  emailAddress VARCHAR(500) NOT NULL,
  PRIMARY KEY (contactID)
);


-- -----------------------------------------------------
-- Table KnownInstruments
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS KnownInstruments (
  personID INT NOT NULL,
  instrument VARCHAR(500) NULL,
  PRIMARY KEY (personID, instrument)
);


-- -----------------------------------------------------
-- Table Person
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Person (
  personID INT NOT NULL,
  addressID INT NOT NULL,
  fullName VARCHAR(500) NOT NULL,
  personNumber VARCHAR(12) NOT NULL,
  PRIMARY KEY (personID)
);


-- -----------------------------------------------------
-- Table Teacher
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Teacher (
  teacherID INT NOT NULL,
  personID INT NOT NULL,
  teachesEnsambles INT NOT NULL,
  PRIMARY KEY (teacherID)
);


-- -----------------------------------------------------
-- Table Price
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Price (
  lessonType INT NOT NULL,
  cost INT NOT NULL,
  PRIMARY KEY (lessonType)
);


-- -----------------------------------------------------
-- Table PersonContact
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PersonContact (
  personID INT NOT NULL,
  contactID INT NOT NULL,
  PRIMARY KEY (personID, contactID)
);


-- -----------------------------------------------------
-- Table StudentInstrument
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS StudentInstrument (
  studentID INT NOT NULL,
  instrumentID INT NOT NULL,
  PRIMARY KEY (studentID, instrumentID)
);


-- -----------------------------------------------------
-- Table LessonTimeSlot
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS LessonTimeSlot (
  lessonID INT NOT NULL,
  timeSlotID INT NOT NULL,
  PRIMARY KEY (timeSlotID, lessonID)
);


-- -----------------------------------------------------
-- Table Skill
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Skill (
  skill INT NOT NULL,
  title VARCHAR(500) NOT NULL,
  PRIMARY KEY (skill)
);


-- -----------------------------------------------------
-- Table LessonType
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS LessonType (
  type INT NOT NULL,
  title VARCHAR(500) NOT NULL,
  PRIMARY KEY (type)
);

