-- MySQL Script generated by MySQL Workbench
-- Minor modifications made by hand by Viggo Hermansson
-- Mon Dec  5 00:26:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema soundgood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soundgood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS soundgood ;

-- -----------------------------------------------------
-- Table soundgood.Instrument
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Instrument (
  instrumentID INT NOT NULL,
  type VARCHAR(500) NOT NULL,
  brand VARCHAR(500) NOT NULL,
  price INT NOT NULL,
  monthRented INT NULL,
  yearRented INT NULL,
  PRIMARY KEY (instrumentID)
);


-- -----------------------------------------------------
-- Table soundgood.Student
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Student (
  studentID INT NOT NULL,
  personID INT NOT NULL,
  admitted INT NOT NULL,
  PRIMARY KEY (studentID)
);


-- -----------------------------------------------------
-- Table soundgood.Siblings
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Siblings (
  studentID INT NOT NULL,
  siblingID INT NOT NULL,
  PRIMARY KEY (studentID, siblingID)
);


-- -----------------------------------------------------
-- Table soundgood.Address
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Address (
  addressID INT NOT NULL,
  street VARCHAR(500) NOT NULL,
  zipCode VARCHAR(500) NOT NULL,
  city VARCHAR(500) NOT NULL,
  PRIMARY KEY (addressID)
);


-- -----------------------------------------------------
-- Table soundgood.StudentLesson
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.StudentLesson (
  studentID INT NOT NULL,
  lessonID INT NOT NULL,
  PRIMARY KEY (studentID, lessonID)
);


-- -----------------------------------------------------
-- Table soundgood.TimeSlot
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.TimeSlot (
  timeSlotID INT NOT NULL,
  teacherID INT NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  PRIMARY KEY (timeSlotID)
);


-- -----------------------------------------------------
-- Table soundgood.Lesson
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Lesson (
  lessonID INT NOT NULL,
  skill INT NOT NULL,
  teacherID INT NOT NULL,
  lessonType INT NOT NULL,
  PRIMARY KEY (lessonID)
);


-- -----------------------------------------------------
-- Table soundgood.GroupLesson
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.GroupLesson (
  lessonID INT NOT NULL,
  maxStudents INT NOT NULL,
  minStudents INT NOT NULL,
  instrument VARCHAR(500) NULL,
  PRIMARY KEY (lessonID)
);


-- -----------------------------------------------------
-- Table soundgood.IndividualLesson
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.IndividualLesson (
  lessonID INT NOT NULL,
  instrument VARCHAR(500) NULL,
  PRIMARY KEY (lessonID)
);


-- -----------------------------------------------------
-- Table soundgood.Ensamble
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Ensamble (
  lessonID INT NOT NULL,
  maxStudents INT NOT NULL,
  minStudents INT NOT NULL,
  genre VARCHAR(500) NOT NULL,
  PRIMARY KEY (lessonID)
);


-- -----------------------------------------------------
-- Table soundgood.Contact
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Contact (
  contactID INT NOT NULL,
  contactTitle VARCHAR(500) NOT NULL,
  phoneNumber VARCHAR(12) NOT NULL,
  emailAddress VARCHAR(500) NOT NULL,
  PRIMARY KEY (contactID)
);


-- -----------------------------------------------------
-- Table soundgood.KnownInstruments
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.KnownInstruments (
  personID INT NOT NULL,
  instrument VARCHAR(500) NULL,
  PRIMARY KEY (personID, instrument)
);


-- -----------------------------------------------------
-- Table soundgood.Person
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Person (
  personID INT NOT NULL,
  teacherID INT NULL,
  studentID INT NULL,
  addressID INT NOT NULL,
  fullName VARCHAR(500) NOT NULL,
  personNumber VARCHAR(12) NOT NULL,
  PRIMARY KEY (personID)
);


-- -----------------------------------------------------
-- Table soundgood.Teacher
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Teacher (
  teacherID INT NOT NULL,
  personID INT NOT NULL,
  teachesEnsambles INT NOT NULL,
  PRIMARY KEY (teacherID)
);


-- -----------------------------------------------------
-- Table soundgood.Price
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Price (
  lessonType INT NOT NULL,
  cost INT NOT NULL,
  PRIMARY KEY (lessonType)
);


-- -----------------------------------------------------
-- Table soundgood.PersonContact
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.PersonContact (
  personID INT NOT NULL,
  contactID INT NOT NULL,
  PRIMARY KEY (personID, contactID)
);


-- -----------------------------------------------------
-- Table soundgood.StudentInstrument
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.StudentInstrument (
  studentID INT NOT NULL,
  instrumentID INT NOT NULL,
  PRIMARY KEY (studentID, instrumentID)
);


-- -----------------------------------------------------
-- Table soundgood.LessonTimeSlot
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.LessonTimeSlot (
  lessonID INT NOT NULL,
  timeSlotID INT NOT NULL,
  PRIMARY KEY (timeSlotID, lessonID)
);


-- -----------------------------------------------------
-- Table soundgood.Skill
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.Skill (
  skill INT NOT NULL,
  title VARCHAR(500) NOT NULL,
  PRIMARY KEY (skill)
);


-- -----------------------------------------------------
-- Table soundgood.LessonType
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS soundgood.LessonType (
  type INT NOT NULL,
  title VARCHAR(500) NOT NULL,
  PRIMARY KEY (type)
);

